In [1]:
import torch
import numpy as np
from tqdm import tqdm

In [2]:
X = np.array([[0, 0],
                  [0, 1],
                  [1, 0],
                  [1, 1]])

Y = np.array([[0], [1], [1], [0]])

X = np.array(X, dtype=np.float64)
Y = np.array(Y, dtype=np.float64)

In [3]:
input_nodes = 2
output_nodes = 1
hidden_nodes = 2

In [4]:
wh = torch.tensor(np.random.uniform(-1, 1.1, (input_nodes, hidden_nodes)), requires_grad=True)
bh = torch.tensor(np.random.uniform(-1, 1.1, hidden_nodes), requires_grad=True)

wo = torch.tensor(np.random.uniform(-1, 1.1, (hidden_nodes, output_nodes)), requires_grad=True)
bo = torch.tensor(np.random.uniform(-1, 1.1, output_nodes), requires_grad=True)

In [5]:
x = torch.tensor(X)
y = torch.tensor(Y)

In [6]:
x

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]], dtype=torch.float64)

In [7]:
def MSE(predicted_y, target_y):
    return torch.mean(torch.pow(predicted_y-target_y, 2))

In [20]:
def SSE(predicted_y, target_y):
    return torch.sum(torch.pow(predicted_y-target_y, 2))

In [8]:
def Binary_Cross_Entropy(predicted_y, target_y):
    return torch.mean(-1 * torch.add(torch.mul(target_y, torch.log(predicted_y)), torch.mul(1-target_y, torch.log(1 - predicted_y))))

In [16]:
def forward_pass():
    zh = torch.matmul(x, wh) + bh
    ah = torch.sigmoid(zh)
    
    zo = torch.matmul(ah, wo) + bo
    ao = torch.sigmoid(zo)
    return ao
    

In [17]:
epochs = 60000
lr = 0.4

In [18]:
BCE_loss = torch.nn.BCELoss()
for epoch in tqdm(range(epochs)):
    predicted_y = forward_pass()
    #loss = Binary_Cross_Entropy(predicted_y, y)
    loss = MSE(predicted_y, y)
    #print("iteration: ", epoch, "loss: ", loss.item(), "loss1: ", BCE_loss(predicted_y, y))
    
    loss.backward()
    
    with torch.no_grad():
        wh -= lr * wh.grad
        bh -= lr * bh.grad
        wo -= lr * wo.grad
        bo -= lr * bo.grad
        
        wh.grad.zero_()
        bh.grad.zero_()
        wo.grad.zero_()
        bo.grad.zero_()
    

  0%|                                                                                            | 0/1 [00:00<?, ?it/s]

tensor([[-4.6260],
        [ 4.5835],
        [ 4.5844],
        [-4.3766]], dtype=torch.float64, grad_fn=<AddBackward0>)


100%|███████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 182.16it/s]


In [13]:
predicted = forward_pass()
predicted
#BCE_loss

tensor([[3.4113e-04],
        [9.9965e-01],
        [9.9965e-01],
        [5.2652e-04]], dtype=torch.float64, grad_fn=<SigmoidBackward>)

In [12]:
predicted = forward_pass()
predicted
#MSE_loss

tensor([[0.0097],
        [0.9899],
        [0.9899],
        [0.0124]], dtype=torch.float64, grad_fn=<SigmoidBackward>)

In [33]:
def get_accuracy(predicted, actual):
    predicted_boolean = predicted.detach().numpy() > 0.97
    actual_boolean = actual > 0.9
    assert len(actual_boolean) == len(predicted_boolean)
    accuracy_boolean = predicted_boolean == actual_boolean
    accuracy = np.count_nonzero(accuracy_boolean)/len(actual)
    return accuracy * 100
    

In [34]:
get_accuracy(predicted, Y)

100.0

In [18]:
loss = torch.nn.BCELoss()
loss(torch.tensor([1.0, 0.0, 1.0]), torch.tensor([1.0, 1.0, 1.0]))

tensor(9.2103)