In [2]:
import torch
import numpy as np
from tqdm import tqdm

ModuleNotFoundError: No module named 'torch'

In [18]:
torch.__version__

'1.3.1'

In [19]:
X = [[0, 0],
    [0, 1],
    [1, 0],
    [1, 1]]
Y = [[0],
    [0],
    [0],
    [1]]
X = np.array(X, dtype=np.float64)
Y = np.array(Y, dtype=np.float64)

In [20]:
INPUT_DIM = 2
NUM_OUTPUT = 1

In [21]:
w = torch.tensor(np.random.uniform(-1, 1.1, (INPUT_DIM, NUM_OUTPUT)), requires_grad=True)
b = torch.tensor(np.random.uniform(-1, 1.1, NUM_OUTPUT), requires_grad=True)

In [22]:
x = torch.tensor(X)
y = torch.tensor(Y)

In [23]:
def MSE(predicted_y, target_y):
    return torch.mean(torch.pow(predicted_y-target_y, 2))

In [24]:
def forward_pass():
    zo = torch.matmul(x, w) + b
    ao = torch.sigmoid(zo)
    return ao
    

In [25]:
forward_pass()

tensor([[0.3140],
        [0.2902],
        [0.3287],
        [0.3043]], dtype=torch.float64, grad_fn=<SigmoidBackward>)

In [26]:
epochs = 60000
lr = 0.4

In [27]:
BCE_loss = torch.nn.BCELoss()
for epoch in tqdm(range(epochs)):
    predicted_y = forward_pass()
    loss = MSE(predicted_y, y)
    #loss = BCE_loss(predicted_y, y)
    #print("iteration: ", epoch, "loss: ", loss.item())
    
    loss.backward()
    
    with torch.no_grad():
        temp = w.grad
        w -= lr * temp
        b -= lr * b.grad
        #print("w.grad: ", w.grad)
        #print("w: ", w)
        #print("w.grad: ", temp)
        
        w.grad.zero_()
        b.grad.zero_()
    
    
    

100%|██████████████████████████████████████████████████████████████████████████| 60000/60000 [00:32<00:00, 1848.62it/s]


In [14]:
forward_pass()
#BCE_loss

tensor([[6.8760e-10],
        [7.8828e-04],
        [7.8828e-04],
        [9.9890e-01]], dtype=torch.float64, grad_fn=<SigmoidBackward>)

In [28]:
forward_pass()
#MSE_loss

tensor([[4.1087e-06],
        [1.4896e-02],
        [1.4896e-02],
        [9.8235e-01]], dtype=torch.float64, grad_fn=<SigmoidBackward>)

In [19]:
y_pred = forward_pass().detach().numpy()

In [23]:
np.count_nonzero(y_pred > 0.95)

1